### ISSUE TITLE
Improve quality scatter logo + branding colors

### ISSUE THREAD

**Issue by kesar** [EOSIO/ual-scatter#21]
<img width="159" alt="Screenshot 2019-04-03 at 13 01 42" src="https://user-images.githubusercontent.com/1288106/55474389-4f841600-5611-11e9-859a-3b908f16bd1b.png">

Logo is pixelated and colors don't match brand identity of Scatter. ( https://get-scatter.com/branding )

SVG would probably give better results: https://github.com/EOSIO/ual-scatter/blob/master/src/scatterLogo.ts

**Comment by chris-allnutt** [comment]
@kesar I will be addressing this, this week.

**Comment by chris-allnutt** [comment]
Will be released this week with the new logo and colors.
