### ISSUE TITLE
cannot connect to the app

### ISSUE THREAD

**Issue by BhaskaranR** [EOSIO/ual-scatter#42]
I have scatter open. But i am not able to connect to scatter
![image](https://user-images.githubusercontent.com/11024551/60107579-2321f680-9735-11e9-93a1-778076719375.png)

**Comment by TaraTritt** [comment]
Hi @BhaskaranR could you post any errors in the console you are receiving and any other information on your current development setup to help us further debug your issue?

**Comment by BhaskaranR** [comment]
i downloaded tokenpocket wallet yesterday. found out that scatter gets messed up with you have token pocket. had to delete it to make it work.

thanks
